# 이름짓기
name: Github Actions로 테스트 자동화하기

# on: 언제 이 작업을 실행할지 정의
# push: github에 push 할때마다 실행
on: push

# jobs: 어떤일을 실행 할지 정의
jobs:
  push-job:
    runs-on: ubuntu-latest
    # 일을 어떤 순서로 진행할지 정의
    steps:
      - name: Github Repository 불러오기
        uses: actions/checkout@v5

      - name: Node.js 설치하기
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: 의존성(라이브러리) 설치
        run: npm ci

      - name: 테스트 실행하기
        run: npm run test
